#server port
server:
  port: 9090

#datasource
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
# MyBatis
mybatis:
    typeAliasesPackage: com.oliver.mybatis.demo.model
    mapperLocations: classpath:/mapper/*Mapper.xml
    configLocation: classpath:/mybatis-config.xml